# Generated by Django 3.2.8 on 2021-10-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(default='1', primary_key=True, serialize=False)),
                ('name', models.CharField(default='name', editable=False, max_length=122, null=True)),
                ('phone', models.CharField(default='phone', editable=False, max_length=12, null=True)),
                ('desc', models.TextField(default='desc', editable=False, max_length=200, null=True)),
                ('date', models.DateField(default='date', editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', editable=False, max_length=122, null=True)),
                ('email', models.CharField(default='email', editable=False, max_length=122, null=True)),
                ('password', models.CharField(default='password', editable=False, max_length=100, null=True)),
            ],
        ),
    ]
